apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: public
  name: traefik-public
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: websecure
    port: 443
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  type: LoadBalancer
